Implement component type
fawaz-ahmed/react-native-read-more pull request #50
Opened 2021-12-29 15:03 UTC by KoreanThinker

I simply defined the type.

```ts
export interface ReadMoreProps {
    style?: StyleProp<TextStyle>;
    seeMoreStyle?: StyleProp<TextStyle>;
    seeLessStyle?: StyleProp<TextStyle>;
    wrapperStyle?: StyleProp<ViewStyle>;
    children?: React.ReactNode;
    numberOfLines?: number;
    seeMoreText?: string;
    seeLessText?: string;
    animate?: boolean;
    customTextComponent?: React.ReactNode;
    ellipsis?: string;
    allowFontScaling?: boolean;
    onExpand?: () => void;
    onCollapse?: () => void;
    expandOnly?: boolean;
    seeMoreOverlapCount?: number;
    debounceSeeMoreCalc?: number;
    onLayout?: (event: LayoutChangeEvent) => void;
    onTextLayout?: (event: NativeSyntheticEvent<TextLayoutEventData>) => void;
    onReady?: () => void;
}
```

2021-12-29 15:04 UTC, KoreanThinker commented
@fawaz-ahmed Please review it.

2021-12-29 15:35 UTC, fawaz-ahmed commented
@KoreanThinker this is a great addition. Thanks for supporting.
Can you also change version in package.json to 2.3.0 ?

2021-12-29 19:47 UTC, fawaz-ahmed commented on package.json
> +    "react": "^16.9.0"
Is this package react needed ?

2021-12-29 19:48 UTC, fawaz-ahmed commented on package.json
>    "version": "2.2.2",
Can you also bump version to 2.3.0 ?

2021-12-29 19:48 UTC, fawaz-ahmed commented on package.json
> +    "react": "^16.9.0"
Since its already installed with every react native app

2021-12-29 23:03 UTC, fawaz-ahmed requested changes
PR looks good and this will help alot moving towards ts. @KoreanThinker just think that the devDependencies are not needed.
Please see comments.

2021-12-29 23:03 UTC, fawaz-ahmed commented on package.json
> +    "@types/react-native": "^0.66.0",
This package is not being used anywhere or am I mistaken. Please check if not then let's remove it

2021-12-29 23:03 UTC, fawaz-ahmed commented on index.d.ts
> +    children?: React.ReactNode;
Children can be a node or multiple nodes.

2021-12-30 03:04 UTC, KoreanThinker commented on index.d.ts
> +    children?: React.ReactNode;
@fawaz-ahmed React.ReactNode can be contain multiple nodes
This code working well.
```tsx
<ReadMore>
   <Text>hi</Text>
   <Icon />
</ReadMore>
```

2021-12-30 03:07 UTC, fawaz-ahmed approved these changes

2021-12-30 03:08 UTC, merged